//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessedFiles
    {
        public int ID { get; set; }
        public int SystemID { get; set; }
        public string FileName { get; set; }
        public string Type { get; set; }
        public System.DateTime FileDate { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public int RowCount { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Systems Systems { get; set; }
    }
}
