//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTowers
    {
        public System.Guid SessionID { get; set; }
        public int SystemID { get; set; }
        public int TowerNumber { get; set; }
        public string TowerNumberHex { get; set; }
        public string Description { get; set; }
        public Nullable<int> HitCount { get; set; }
        public string WACN { get; set; }
        public string ControlCapabilities { get; set; }
        public string Flavor { get; set; }
        public string CallSigns { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public System.DateTime FirstSeen { get; set; }
        public System.DateTime LastSeen { get; set; }
    }
}
