//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTowerFrequencyUsage
    {
        public System.Guid SessionID { get; set; }
        public int SystemID { get; set; }
        public int TowerID { get; set; }
        public string Channel { get; set; }
        public string Frequency { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> AffiliationCount { get; set; }
        public Nullable<int> DeniedCount { get; set; }
        public Nullable<int> VoiceGrantCount { get; set; }
        public Nullable<int> EmergencyVoiceGrantCount { get; set; }
        public Nullable<int> EncryptedVoiceGrantCount { get; set; }
        public Nullable<int> DataCount { get; set; }
        public Nullable<int> PrivateDataCount { get; set; }
        public Nullable<int> CWIDCount { get; set; }
        public Nullable<int> AlertCount { get; set; }
        public System.DateTime FirstSeen { get; set; }
        public System.DateTime LastSeen { get; set; }
    }
}
