//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Towers()
        {
            this.TempTowerFrequencies = new HashSet<TempTowerFrequencies>();
            this.TowerFrequencies = new HashSet<TowerFrequencies>();
            this.TowerFrequencyUsage = new HashSet<TowerFrequencyUsage>();
        }
    
        public int ID { get; set; }
        public int SystemID { get; set; }
        public int TowerNumber { get; set; }
        public string TowerNumberHex { get; set; }
        public string Description { get; set; }
        public Nullable<int> HitCount { get; set; }
        public string WACN { get; set; }
        public string ControlCapabilities { get; set; }
        public string Flavor { get; set; }
        public string CallSigns { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public System.DateTime FirstSeen { get; set; }
        public System.DateTime LastSeen { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Systems Systems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempTowerFrequencies> TempTowerFrequencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TowerFrequencies> TowerFrequencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TowerFrequencyUsage> TowerFrequencyUsage { get; set; }
    }
}
