//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TowerFrequencies
    {
        public int ID { get; set; }
        public int SystemID { get; set; }
        public int TowerID { get; set; }
        public string Channel { get; set; }
        public string Usage { get; set; }
        public string Frequency { get; set; }
        public string InputChannel { get; set; }
        public string InputFrequency { get; set; }
        public Nullable<int> InputExplicit { get; set; }
        public Nullable<int> HitCount { get; set; }
        public System.DateTime FirstSeen { get; set; }
        public System.DateTime LastSeen { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Towers Towers { get; set; }
    }
}
